[project]
name = "dbt-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thiru", email = "thirupati.info@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.12.4",
    "dbt-databricks>=1.10.9",
]

[project.scripts]
dbt-project = "dbt_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
